### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by hamadash** [hamadash/rails-app-example#1]
- [x] `rails new` する
  - Dockerfileを用意

- [x] posts の crud を作成

- [ ] timezoneを調整

- [x] erb から slim に変更

- [ ] rubocop を追加

- [ ] ridgepole を追加

- [ ] etc
